### ISSUE TITLE
bot is unable to send songs

### ISSUE THREAD

**Issue by ghost** [gsoosk/TelegramSpotifyDownloader#2]
Here's Logs :- https://nekobin.com/furorufote
Screens below .
![Screenshot_2021-01-22-01-03-18-61](https://user-images.githubusercontent.com/72996121/105402625-a70fcd80-5c4d-11eb-946a-0b0586d0593c.png)

**Comment by gsoosk** [comment]
Hi, 
Which downloader are you using?  SpotifyDL or SpotDL?

**Comment by bhardwajjEE** [comment]
SpotifyDL ...
![IMG_20210122_141903](https://user-images.githubusercontent.com/72996121/105468284-d4e02b00-5cbc-11eb-9d87-5f46d4651acf.jpg)

**Comment by gsoosk** [comment]
Did you install it using the below command on your machine?
```
npm install -g spotify-dl
```

**Comment by ghost** [comment]
no ...😅 
btw i tried Changing Downloader .
& it didn't worked on both..

**Comment by ghost** [comment]
One Suggestion :- try Improving UI , try adding Commands .

**Comment by gsoosk** [comment]
> no ...
> btw i tried Changing Downloader .
> & it didn't worked on both..

You should install the requirements first to run the bot properly. I recommend you install them using the guidance in the README.

**Comment by gsoosk** [comment]
> One Suggestion :- try Improving UI , try adding Commands .

Yes, that would be great! 
Unfortunately, I am not free currently. However, any pull request is more than welcomed by me.
